### ISSUE TITLE
Roi: loading line profile

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#859]
Using the current master, the following produces a bug when trying to load a line profile mode using Line2DROI.
```python
import hyperspy.api as hs
import numpy as np

image_array = np.arange(10000).reshape(100,100)
s = hs.signals.Image(image_array)
roi = hs.roi.Line2DROI(10,10,20,20,5)
s_line = roi(s)
s_line.save("s_line.hdf5")
s_line.plot() # This works

s2_line = hs.load("s_line.hdf5") # This does not work
```

With the error:
```python
axes.py in set_signal_dimension(self, value)
    896             raise ValueError(
    897                 "The signal dimension cannot be greater"
--> 898                 " than the number of axes which is %i" % len(self._axes))
    899         elif value < 0:
    900             raise ValueError(

ValueError: The signal dimension cannot be greater than the number of axes which is 1
```

**Comment by to266** [comment]
I'll add the bugfix to https://github.com/hyperspy/hyperspy/pull/844
If you want to use it in the mean time, just change 
`s_line.metadata.Signal.record_by` from `"image"` to `"spectrum"` or an empty line.

**Comment by magnunor** [comment]
Was this fixed in #844? If yes, we can close this issue.

**Comment by vidartf** [comment]
A fix is present in #844, but since #844 isn't merged yet, this issue is still present in master. Will close once #844 is merged.

**Comment by magnunor** [comment]
Closing since https://github.com/hyperspy/hyperspy/pull/844 has been merged
